# Basic Python Programming

### Print

In [1]:
print ("Hello World")

Hello World


In [8]:
print (2+3)

5


### Print dengan string formatting


- `%` old method, 
- `%s` formating string, 
- `%.2f` formating float 2 digit decimal, 
- `%d` formating integer 


- `'{} {}'.format()` new method,


In [54]:
print("nilai %s " % str(100))

nilai 100 


In [56]:
print("nilai %d " % 100)

nilai 100 


In [60]:
print("nilai %s " % (100.05 + 10.003))

nilai 110.053 


In [61]:
print("nilai %.2f " % (100.05 + 10.003))

nilai 110.05 


### Print tuple
- tuple dalam python berbentuk `(value1, value2, value3)`

In [16]:
print("nilai ", 2 + 3, " adalah bilangan ganjil")

nilai  5  adalah bilangan ganjil


### Kometar
- pada python menggunakan tanga `#` atau `"""` untuk multiple comment

In [7]:
# ini program print
print ("Helo World") 

"""
Multiple
Comment
in Python
"""
print("Hello World 2")

Helo World
Hello World 2


### Help & Documentation
- Gunakan `help()` dan `dir()` untuk melihat detail package yang digunakan
- contohnya kita akan coba import libraray `math`

In [17]:
import math

In [18]:
dir(math)

['__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'pi',
 'pow',
 'radians',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc']

In [19]:
help(math)

Help on built-in module math:

NAME
    math

DESCRIPTION
    This module is always available.  It provides access to the
    mathematical functions defined by the C standard.

FUNCTIONS
    acos(...)
        acos(x)
        
        Return the arc cosine (measured in radians) of x.
    
    acosh(...)
        acosh(x)
        
        Return the inverse hyperbolic cosine of x.
    
    asin(...)
        asin(x)
        
        Return the arc sine (measured in radians) of x.
    
    asinh(...)
        asinh(x)
        
        Return the inverse hyperbolic sine of x.
    
    atan(...)
        atan(x)
        
        Return the arc tangent (measured in radians) of x.
    
    atan2(...)
        atan2(y, x)
        
        Return the arc tangent (measured in radians) of y/x.
        Unlike atan(y/x), the signs of both x and y are considered.
    
    atanh(...)
        atanh(x)
        
        Return the inverse hyperbolic tangent of x.
    
    ceil(...)
        ceil(x)
        
 

In [20]:
help(math.asin)

Help on built-in function asin in module math:

asin(...)
    asin(x)
    
    Return the arc sine (measured in radians) of x.



### Variable
- Dapat diawali huruf atau `_` (underscore)

In [21]:
_umur = 20

In [23]:
type(_umur)

int

In [24]:
_umur = '20'

In [25]:
type(_umur)

str

In [26]:
_umur = False

In [27]:
type(_umur)

bool

In [28]:
_umur = [20, "hi", 3.14]

In [29]:
type(_umur)

list

In [33]:
_umur = set([20, "hi", 3.14])

In [34]:
type(_umur)

set

In [35]:
_umur

{20, 3.14, 'hi'}

### Casting variable atau type conversion
```
int() untuk mengubah menjadi integer;
long() untuk mengubah menjadi integer panjang;
float() untuk mengubah menjadi float;
bool() untuk mengubah menjadi boolean;
chr() untuk mengubah menjadi karakter;
str() untuk mengubah menjadi string.
bin() untuk mengubah menjadi bilangan Biner.
hex() untuk mengubah menjadi bilangan Heksadesimal.
oct() untuk mengubah menjadi bilangan okta.
```

In [36]:
_umur = 30

In [37]:
type(_umur)

int

In [38]:
_umur = str(_umur)

In [39]:
type(_umur)

str

In [40]:
nilai = 2+3
print ("nilai " + str(nilai))

nilai 5


### Input & Ouput
- dapat menggunakan perintah `input()` yang akan mengembalikan data dengan tipe data string

In [42]:
data = input("data :")

print(type(data))

data :test
<class 'str'>


In [44]:
A = input("A :")
B = input("B :")

C = int(A) + int(B)
print ("A + B = " + str(C) )

A :1
B :2
A + B = 3


### Operator Aritmatika

```
+ untuk operator penjumlahan
- untuk operator pengurangan
/ untuk operator pembagian
* untuk operator perkalian
% untuk operator modulo (hasil sisa pembagian)
** untuk operator pangkat
```

In [46]:
# Ambil input untuk mengisi nilai
a = int(input("Inputkan nilai a: "))
b = int(input("Inputkan nilai b: "))

# Menggunakan operator penjumlahan
c = a + b
print ("Hasil %d + %d = %d" % (a,b,c))


Inputkan nilai a: 4
Inputkan nilai b: 56
Hasil 4 + 56 = 60


In [47]:
# Operator Pengurangan
c = a - b
print ("Hasil %d - %d = %d" % (a,b,c))

Hasil 4 - 56 = -52


In [48]:
# Operator Perkalian
c = a * b
print ("Hasil %d * %d = %d" % (a,b,c))

Hasil 4 * 56 = 224


In [69]:
# Operator Pembagian
c = a / b
print ("Hasil %d / %d = %d" % (a,b,c))

Hasil 4 / 56 = 0


In [70]:
c = a / b
print ("Hasil %d / %d = %f" % (a,b,c))

Hasil 4 / 56 = 0.071429


In [50]:
# Operator Sisa Bagi
c = a % b
print ("Hasil %d %% %d = %d" % (a,b,c))

Hasil 4 % 56 = 4


In [63]:
# Operator Pangkat
c = a ** b
print ("Hasil %d ** %d = %d" % (a,b,c))

Hasil 4 ** 56 = 5192296858534827628530496329220096


### Operator Penugasan

```
a = 1 operator penugasan mengisi nilai
a +=1 operator penugasan menambahkan 1 ke variable a
a -=1 operator penugasan mengurangkan 1 ke variable a
a *=2 operator penugasan mengalikan 2 ke variable a
a /= 2 operator penugasan membagikan 2 ke variable a
```

In [73]:

a = 8
print("nilai awal \t", a)

a += 1
print("ditambah 1 \t", a)

a *= 2
print("dikali 2 \t", a)

a -= 5
print("dikurang 5 \t", a)

a /= 2
print("dibagi 2 \t", a)

nilai awal 	 8
ditambah 1 	 9
dikali 2 	 18
dikurang 5 	 13
dibagi 2 	 6.5


### Operator Pembanding
```
== operator pembanding "sama dengan", a == b
!= operator pembanding "tidak sama dengan", a != b
< operator pembanding "lebih kecil dari", a < b
> operator pembanding "lebih besar dari", a > b
<= operator pembanding "lebih kecil dari sama dengan", a <= b
> operator pembanding "lebih besar dari sama dengan", a >= b
```

In [74]:
a = int(input("Inputkan nilai a: "))
b = int(input("Inputkan nilai b: "))

# apakah a sama dengan b?
c = a == b
print ("Apakah %d == %d: %r" % (a,b,c))


Inputkan nilai a: 4
Inputkan nilai b: 5
Apakah 4 == 5: False


In [75]:
# apakah a < b?
c = a < b
print ("Apakah %d < %d: %r" % (a,b,c))

Apakah 4 < 5: True


In [76]:
# apakah a > b?
c = a > b
print ("Apakah %d > %d: %r" % (a,b,c))

Apakah 4 > 5: False


In [77]:
# apakah a <= b?
c = a <= b
print ("Apakah %d <= %d: %r" % (a,b,c))


Apakah 4 <= 5: True


In [78]:
# apakah a >= b?
c = a >= b
print ("Apakah %d >= %d: %r" % (a,b,c))

Apakah 4 >= 5: False


In [79]:
# apakah a != b?
c = a != b
print ("Apakah %d != %d: %r" % (a,b,c))

Apakah 4 != 5: True


### Operator Logika

- Logika AND

| AND   | True  | False |
|-------|-------|-------|
| True  | True  | False |
| False | False | False |

- Logika OR

|  OR   | True  | False |
|-------|-------|-------|
| True  | True  | True  |
| False | True  | False |

- Logika Not

|       | NOT   |
|-------|-------|
| True  | False |
| False | True  |

In [80]:
a = True
b = False


In [81]:
# Logika AND
c = a and b
print ("%r and %r = %r" % (a,b,c))

True and False = False


In [82]:
# Logika OR
c = a or b
print ("%r or %r = %r" % (a,b,c))

True or False = True


In [83]:
# Logika Not
c = not a
print ("not %r  = %r" % (a,c))

not True  = False


### Percabangan (If, elif, else)

struktur percabangan pada python :

```
if statement_1 :
    tugas_1
elif statement_2 :
    tugas_2
else :
    tugas_3

```

In [86]:
lulus = input("Apakah kamu lulus? [ya/tidak]: ")
if lulus == "tidak":
    print("Kamu harus ikut ujian")

Apakah kamu lulus? [ya/tidak]: tidak
Kamu harus ikut ujian


In [88]:
umur = int(input("Berapa umur kamu: "))
if umur >= 18:
    print("Kamu boleh membuat SIM")
else:
    print("Kamu belum boleh membuat SIM")

Berapa umur kamu: 19
Kamu boleh membuat SIM


In [ ]:
umur = int(input("Berapa umur kamu: "))
umur = int(input("Berapa umur kamu: "))

### Perbedaan multiple if statement dan elif statement

- jika multiple `if` statment maka program akan cek **semua if statement** (tidak ada yang terlewatkan) dan bisa jadi semua instruksi bisa dilakukan jika memang memnuhi kondisi semua multiple if statement. 


- Namun jika `elif` statement **tidak semua dicek** (bisa semua/bisa tidak), program akan cek semua kondisi jika program masih belum menemukan yang sesuai, namun **jika ada yang sesuai** maka program akan langsung **keluar dari statement pecabangan**.

In [89]:
nilai = int(input("Inputkan nilaimu: "))

if nilai >= 90:
    grade = "A"
elif nilai >= 80:
    grade = "B+"
elif nilai >= 70:
    grade = "B"
elif nilai >= 60:
    grade = "C+"
elif nilai >= 50:
    grade = "C"
elif nilai >= 40:
    grade = "D"
else:
    grade = "E"

print("Grade: %s" % grade)

Inputkan nilaimu: 80
Grade: B+


In [90]:
nilai = int(input("Inputkan nilaimu: "))

if nilai >= 90:
    grade = "A"
if nilai >= 80:
    grade = "B+"
if nilai >= 70:
    grade = "B"
if nilai >= 60:
    grade = "C+"
if nilai >= 50:
    grade = "C"
if nilai >= 40:
    grade = "D"
else:
    grade = "E"

print("Grade: %s" % grade)

Inputkan nilaimu: 80
Grade: D


### Perulangan mengunakan for

- perulangan pada pemrograman python hanya mengimplementasikan *collection-based iteration*, 
- sehingga sebuah perulangan bisa dilakukan jika kita memiliki **iterable** object di python

```
for <var> in <iterable>:
    <statement(s)>

```

- Iterable pada python adalah object dalam bentuk `string`, `list`, `tuple`, `dictionary`, `set`

- contoh bentuk perulangan dari iterator `list`

In [104]:
myList = ['satu', 'dua', 'tiga']

print(type(myList))

for item in myList :
    print ("item", item)

<class 'list'>
item satu
item dua
item tiga


- contoh bentuk perulangan dari iterator `tuple`

In [105]:
myTuple = ('satu', 'dua', 'tiga')

print(type(myTuple))

for item in myTuple :
    print ("item", item)

<class 'tuple'>
item satu
item dua
item tiga


- contoh bentuk perulangan dari iterator `set`

In [106]:
mySet = {'satu', 'dua', 'tiga'}

print(type(mySet))

for item in mySet :
    print ("item", item)

<class 'set'>
item satu
item dua
item tiga


- contoh bentuk perulangan dari iterator `dictionary`

In [107]:
myDict = {'satu': 1, 'dua': 2, 'tiga': 3}

print(type(myDict))

for item in myDict :
    print ("item", item)

<class 'dict'>
item satu
item dua
item tiga


### Perulangan menggunakan while

- struktur dasar,

```
while <condition>:
    <do something..>
```

In [110]:
i = 0
while i <= 10 :
    print("loop ke-", i)
    i +=1

loop ke- 0
loop ke- 1
loop ke- 2
loop ke- 3
loop ke- 4
loop ke- 5
loop ke- 6
loop ke- 7
loop ke- 8
loop ke- 9
loop ke- 10


### fungsi range() 
- fungsi `range` digunakan untuk menghasilkan *sequence* angka

In [114]:
A = range(1, 10)

print(type(A))

<class 'range'>


kita dapat gunakan :


+ fungsi `list()` untuk convert object `range` menjadi list
+ fungsi `set()` untuk convert object `range` menjadi set
+ fungsi `tuple()` untuk convert object `range` menjadi tuple

In [115]:
B = list(A)

print(B, type(B))

[1, 2, 3, 4, 5, 6, 7, 8, 9] <class 'list'>


In [116]:
B = set(A)

print(B, type(B))

{1, 2, 3, 4, 5, 6, 7, 8, 9} <class 'set'>


In [118]:
B = tuple(A)

print(B, type(B))

(1, 2, 3, 4, 5, 6, 7, 8, 9) <class 'tuple'>


### mengunakan range() pada perulangan for

In [119]:
for i in range(10):
    print ("iterasi ke-", i)

iterasi ke- 0
iterasi ke- 1
iterasi ke- 2
iterasi ke- 3
iterasi ke- 4
iterasi ke- 5
iterasi ke- 6
iterasi ke- 7
iterasi ke- 8
iterasi ke- 9


In [120]:
for i in range(2, 10):
    print ("iterasi ke-", i)

iterasi ke- 2
iterasi ke- 3
iterasi ke- 4
iterasi ke- 5
iterasi ke- 6
iterasi ke- 7
iterasi ke- 8
iterasi ke- 9


In [121]:
for i in range(2, 10, 2):
    print ("iterasi ke-", i)

iterasi ke- 2
iterasi ke- 4
iterasi ke- 6
iterasi ke- 8


### Struktur Data

#### List
- heterogen

In [122]:
myList = [ 10, 'hello', 14.5, False, [1, 3, 4], (1, 2, 4)]

- akses seluruh elemen list

In [123]:
myList

[10, 'hello', 14.5, False, [1, 3, 4], (1, 2, 4)]

- akses 1 elemen pada list
- menggunakan positive index (dimulai dari index = 0 dari sisi kiri ujung)

In [124]:
myList[0]

10

In [127]:
myList[3]

False

In [128]:
myList[6]

IndexError: list index out of range

- menggunakan negative index (dimulai dari index = -1 dari sisi kanan ujung)

In [129]:
myList[-1]

(1, 2, 4)

In [130]:
myList[-4]

14.5

In [133]:
myList[-7]

IndexError: list index out of range

- slicing pada list dengan menggunakan `:`

In [135]:
myList[1:4]

['hello', 14.5, False]

In [136]:
myList[:3]

[10, 'hello', 14.5]

In [137]:
myList[3:]

[False, [1, 3, 4], (1, 2, 4)]

In [138]:
myList[:-1]

[10, 'hello', 14.5, False, [1, 3, 4]]

In [139]:
myList[1:-3]

['hello', 14.5]

In [140]:
myList[:]

[10, 'hello', 14.5, False, [1, 3, 4], (1, 2, 4)]

In [144]:
myList[4][:2]

[1, 3]

- list bersifat **mutable**, sehingga kita bisa **reassign** dan **delete** elemen list

In [146]:
myList[0] = 21

In [147]:
myList

[21, 'hello', 14.5, False, [1, 3, 4], (1, 2, 4)]

In [148]:
myList[0:2] = [33, 'world'] 

In [149]:
myList

[33, 'world', 14.5, False, [1, 3, 4], (1, 2, 4)]

In [150]:
myList = [10, 'hello', 14.5, False, [1, 3, 4], (1, 2, 4)]

In [151]:
myList

[10, 'hello', 14.5, False, [1, 3, 4], (1, 2, 4)]

In [152]:
del myList[0]

myList

['hello', 14.5, False, [1, 3, 4], (1, 2, 4)]

In [153]:
del myList[0:2]

myList

[False, [1, 3, 4], (1, 2, 4)]

- builtin function pada list `append()`, `insert()`, `len()`, dll

In [172]:
myList.append(2)

In [173]:
myList

[False, [1, 3, 4], (1, 2, 4), 2]

In [175]:
myList.count(False)

1

In [176]:
myList.insert(1, 3.14)

myList

[False, 3.14, [1, 3, 4], (1, 2, 4), 2]

In [178]:
myList.index(3.14)

1

In [180]:
len(myList)

5

#### Tuple
- heterogen tapi **immutable** item (item tidak dapat di **reassign** atau di **delete**) 

In [154]:
myTuple = (10, 'hello', 14.5, False, [1, 3, 4], (1, 2, 4))

In [155]:
myTuple[0] = 23

TypeError: 'tuple' object does not support item assignment

In [156]:
del myTuple[0]

TypeError: 'tuple' object doesn't support item deletion

- tuple packing

In [159]:
myTuple = 1, 2, 3

In [160]:
myTuple

(1, 2, 3)

- tuple unpacking

In [161]:
x, y, z = myTuple

In [162]:
x

1

In [163]:
y

2

In [164]:
z

3

- builtin function pada tuple

In [181]:
myTuple.count(1)

1

In [182]:
myTuple.index(1)

0

In [183]:
len(myTuple)

3

#### Set
- tidak menyimpan data duplikat

In [165]:
mySet = {1, 3, 2}

In [166]:
mySet

{1, 2, 3}

In [167]:
mySet[0]

TypeError: 'set' object does not support indexing

In [168]:
del mySet[0]

TypeError: 'set' object doesn't support item deletion

In [169]:
mySet[0] = 5

TypeError: 'set' object does not support item assignment

In [170]:
mySet = {1, 3, 2, 3, 5, 5}

In [171]:
mySet

{1, 2, 3, 5}

- set support built in function `discard()`, `pop()`, `clear()`, `remove()`, `add()`, `len()`, dan `max()`

In [184]:
mySet.add(7)

mySet

{1, 2, 3, 5, 7}

In [186]:
mySet.pop()

1

In [187]:
mySet

{2, 3, 5, 7}

In [188]:
mySet.remove(5)

In [189]:
mySet

{2, 3, 7}

In [190]:
len(mySet)

3

### Dictionary

- berpasangan dalam bentuk key-value 

In [192]:
myDictionary = {
    "key 1"    : 10,
    "key 2"    : 13.5,
    "data"     : "Hello World",
    "list_key" : [1, "hello", 3.4, True],
    "dict lv2" : {
        "key 1" : 23.5,
        "data"  : False
    },
    10         : "hi",
    14.77      : False
}

In [193]:
myDictionary

{'key 1': 10,
 'key 2': 13.5,
 'data': 'Hello World',
 'list_key': [1, 'hello', 3.4, True],
 'dict lv2': {'key 1': 23.5, 'data': False},
 10: 'hi',
 14.77: False}

In [194]:
myDictionary['key 1']

10

In [195]:
myDictionary['list_key']

[1, 'hello', 3.4, True]

In [196]:
myDictionary[14.77]

False

In [197]:
myDictionary['data'] = "Hello World Update!"

In [198]:
myDictionary

{'key 1': 10,
 'key 2': 13.5,
 'data': 'Hello World Update!',
 'list_key': [1, 'hello', 3.4, True],
 'dict lv2': {'key 1': 23.5, 'data': False},
 10: 'hi',
 14.77: False}

In [199]:
del myDictionary['key 2']

In [200]:
myDictionary

{'key 1': 10,
 'data': 'Hello World Update!',
 'list_key': [1, 'hello', 3.4, True],
 'dict lv2': {'key 1': 23.5, 'data': False},
 10: 'hi',
 14.77: False}

- built in function pada dictionary

In [201]:
len(myDictionary)

6

In [204]:
myDictionary.get('key 1')

10

In [205]:
myDictionary.get('data')

'Hello World Update!'

In [208]:
myDictionary.keys()

dict_keys(['key 1', 'data', 'list_key', 'dict lv2', 10, 14.77])

In [209]:
myDictionary.values()

dict_values([10, 'Hello World Update!', [1, 'hello', 3.4, True], {'key 1': 23.5, 'data': False}, 'hi', False])

---
___
***

# Basic Numpy 

- **Size** - Numpy data structures take up less space
- **Performance** - they have a need for speed and are faster than lists
- **Functionality** - SciPy and NumPy have optimized functions such as linear algebra operations built in.

In [210]:
import numpy as np

### Create 1D Vector

In [213]:
# vector row

vector_row = np.array([1,2,3])

print(vector_row)

[1 2 3]


In [214]:
# vector column

vector_column = np.array([[1],[2],[3]])

print(vector_column)

[[1]
 [2]
 [3]]


### Create 2D Vector

In [215]:
matrix = np.array([[1,2,3],[4,5,6]])

print(matrix)

[[1 2 3]
 [4 5 6]]


### Akses elemen Vector

In [217]:
matrix[0]

array([1, 2, 3])

In [220]:
matrix[:1]

array([[1, 2, 3]])

In [224]:
matrix[:, :1]

array([[1],
       [4]])

In [225]:
matrix[:, 1:2]

array([[2],
       [5]])

In [226]:
matrix[:, 2:3]

array([[3],
       [6]])

### Vector Data Type

In [254]:
matrix.dtype

dtype('uint32')

In [248]:
matrix = matrix.astype(np.uint16)

In [249]:
matrix.dtype

dtype('uint16')

In [250]:
matrix.nbytes

12

In [251]:
matrix = matrix.astype(np.uint32)

In [252]:
matrix.dtype

dtype('uint32')

In [253]:
matrix.nbytes

24

### Describe Vector

In [255]:
matrix.shape # baris, kolom

(2, 3)

In [256]:
matrix.shape[1]

3

In [257]:
matrix.size

6

In [258]:
matrix.ndim

2

### Builtin Function

In [259]:
matrix

array([[1, 2, 3],
       [4, 5, 6]], dtype=uint32)

In [260]:
np.max(matrix)

6

In [261]:
np.min(matrix)

1

In [262]:
np.mean(matrix)

3.5

In [263]:
np.median(matrix)

3.5

In [264]:
np.std(matrix)

1.707825127659933

In [265]:
np.var(matrix)

2.9166666666666665

In [269]:
np.power(1.707825127659933, 2)

2.9166666666666665

In [267]:
np.sqrt(2.9166666666666665)

1.707825127659933

In [272]:
np.amax(matrix, axis=1) # 1 : kolom, 0 : baris

array([3, 6], dtype=uint32)

In [275]:
np.argmax(matrix, axis=1)

array([2, 2], dtype=int64)

### Reshape Matrix

In [277]:
matrix

array([[1, 2, 3],
       [4, 5, 6]], dtype=uint32)

In [278]:
np.reshape(matrix, (3,2))

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=uint32)

In [279]:
np.reshape(matrix, (1,6))

array([[1, 2, 3, 4, 5, 6]], dtype=uint32)

In [285]:
np.reshape(matrix, (6,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]], dtype=uint32)

### Matrix Operation

In [283]:
A = np.array([[1, 3, 1],
              [5, 2, 1]])

B = np.array([[0, 0, 1],
              [3, 5, 1]])

#### Penjumlahan Matrix

![](resource/penjumlahan_matrix.PNG)

In [284]:
A + B

array([[1, 3, 2],
       [8, 7, 2]])

In [302]:
A - B

array([[ 1,  3,  0],
       [ 2, -3,  0]])

#### Perkalian Skalar

![](resource/perkalian_scalar_matrix.PNG)

In [286]:
2 * A

array([[ 2,  6,  2],
       [10,  4,  2]])

In [287]:
3.5 * B

array([[ 0. ,  0. ,  3.5],
       [10.5, 17.5,  3.5]])

In [303]:
1 / A

array([[1.        , 0.33333333, 1.        ],
       [0.2       , 0.5       , 1.        ]])

In [305]:
B / 2

array([[0. , 0. , 0.5],
       [1.5, 2.5, 0.5]])

#### Perkalian matrix biasa

$\begin{bmatrix} 1 & 3 & 1 \\ 5 & 2 & 1 \end{bmatrix} \begin{bmatrix} 0 & 0 & 1 \\ 3 & 5 & 1 \end{bmatrix} = \begin{bmatrix} 1\times0 & 1\times0 & 1\times1 \\ 5\times3 & 2\times5 & 1\times1 \end{bmatrix} = \begin{bmatrix} 0 & 0 & 1 \\ 15 & 10 & 1 \end{bmatrix}$

In [301]:
A*B

array([[ 0,  0,  1],
       [15, 10,  1]])

In [306]:
B/A

array([[0. , 0. , 1. ],
       [0.6, 2.5, 1. ]])

In [308]:
2 * B / A

array([[0. , 0. , 2. ],
       [1.2, 5. , 2. ]])

#### Transpose Matrix

![](resource/transpose_matrix.PNG)

In [288]:
np.transpose(A)

array([[1, 5],
       [3, 2],
       [1, 1]])

In [289]:
A.T

array([[1, 5],
       [3, 2],
       [1, 1]])

#### Matrix multiplication (dot product)

![](resource/dot_product.PNG)

- hanya dapat dilakukan jika dan hanya jika jumlah kolom pada matrix kiri sama dengan jumlah baris pada matrix kanan. \
$(M, n)(n, m)$ \
untuk, 
$(M, n)$ merupakan ukuran matrix dibagian kanan, \
$(n, m)$ merupakan ukuran matrix dibagian kiri, \
dan akan menghasilkan matrix dengan ukuran $(M, m)$


- Contoh :


$X = \begin{bmatrix} 1 & 2 & 1 \\ 3 & 0 & 1 \end{bmatrix}$

- size X adalah 2, 3

$Y = \begin{bmatrix} 0 & 3 \\ 5 & 1 \\ 7 & 3\end{bmatrix}$

- size Y adalah 3, 2


- sehingga kedua matrix diatas dapat dilakukan operasi dot untuk size (2, `3`)(`3`, 2)


In [294]:
X = np.array([[1, 2, 1],
              [3, 0, 1]])

Y = np.array([[0, 3],
              [5, 1],
              [7, 3]])

In [295]:
X.shape, Y.shape

((2, 3), (3, 2))

In [296]:
np.dot(X, Y)

array([[17,  8],
       [ 7, 12]])

In [298]:
X = np.reshape(X, (1, 6))

X

array([[1, 2, 1, 3, 0, 1]])

In [299]:
Y = np.reshape(Y, (6, 1))

Y

array([[0],
       [3],
       [5],
       [1],
       [7],
       [3]])

In [300]:
np.dot(X, Y)

array([[17]])

#### Generating Random Value

In [309]:
#Generate 3 random integers b/w 1 and 10
print(np.random.randint(0,11,3))

[ 2  4 10]


In [312]:
#Draw 3 numbers from a normal distribution with mean 1.0 and std 2.0
print(np.random.normal(1.0, 2.0, 3))

[-0.82393664  1.78552686  0.97871321]


---
___
***

# Basic Pandas 

- Dapat membaca dan menulis keberbagai format data (TXT, CSV, XLSX, SQL, HDFS, dll)
- Representasi data dalam bentuk tabular yang disebut dengan dataframe (simple dan mudah difahami)
- less writing and more work done
- kecepatan pemrosesan dan kemamuan menghandle data yang sangat besar
- memiliki feature yang kaya untuk pengolahan data (read/write, filtering, sorting, merging, joining, analisis time series, visualization, dll)



In [315]:
import pandas as pd

### Membaca file CSV

Dataset : https://www.kaggle.com/ardisragen/indonesia-coronavirus-cases?select=patient.csv

In [369]:
covid_19 = pd.read_csv('data/datasets_557740_1083090_patient.csv')

In [370]:
covid_19.head()

patient_id  gender   age nationality     province current_state  \
0           1  female  31.0   indonesia  DKI Jakarta      released   
1           2  female  64.0   indonesia  DKI Jakarta      released   
2           3  female  33.0   indonesia  DKI Jakarta      released   
3           4  female  34.0   indonesia  DKI Jakarta      isolated   
4           5    male  55.0   indonesia  DKI Jakarta      isolated   

   contacted_with confirmed_date released_date deceased_date  \
0             NaN       2-Mar-20     13-Mar-20           NaN   
1             1.0       2-Mar-20     16-Mar-20           NaN   
2             1.0       6-Mar-20     13-Mar-20           NaN   
3             1.0       6-Mar-20           NaN           NaN   
4             1.0       8-Mar-20           NaN           NaN   

               hospital  
0  RSPI Sulianti Saroso  
1  RSPI Sulianti Saroso  
2  RSPI Sulianti Saroso  
3  RSPI Sulianti Saroso  
4       RS Persahabatan

In [371]:
covid_19.head(10)

patient_id  gender   age nationality     province current_state  \
0           1  female  31.0   indonesia  DKI Jakarta      released   
1           2  female  64.0   indonesia  DKI Jakarta      released   
2           3  female  33.0   indonesia  DKI Jakarta      released   
3           4  female  34.0   indonesia  DKI Jakarta      isolated   
4           5    male  55.0   indonesia  DKI Jakarta      isolated   
5           6    male  36.0   indonesia  DKI Jakarta      released   
6           7  female  54.0   indonesia  DKI Jakarta      released   
7           8    male  55.0   indonesia  DKI Jakarta      released   
8           9  female  55.0   indonesia  DKI Jakarta      released   
9          10    male  29.0   foreigner  DKI Jakarta      isolated   

   contacted_with confirmed_date released_date deceased_date  \
0             NaN       2-Mar-20     13-Mar-20           NaN   
1             1.0       2-Mar-20     16-Mar-20           NaN   
2             1.0       6-Mar-20     13-Mar-20           NaN   
3             1.0       6-Mar-20           NaN           NaN   
4             1.0       8-Mar-20           NaN           NaN   
5             NaN       8-Mar-20     11-Mar-20           NaN   
6             8.0       9-Mar-20           NaN           NaN   
7             NaN       9-Mar-20           NaN           NaN   
8             NaN       9-Mar-20           NaN           NaN   
9             1.0       9-Mar-20           NaN           NaN   

               hospital  
0  RSPI Sulianti Saroso  
1  RSPI Sulianti Saroso  
2  RSPI Sulianti Saroso  
3  RSPI Sulianti Saroso  
4       RS Persahabatan  
5       RS Persahabatan  
6                   NaN  
7                   NaN  
8                   NaN  
9  RSPI Sulianti Saroso

In [372]:
covid_19.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 893 entries, 0 to 892
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   patient_id      893 non-null    int64  
 1   gender          156 non-null    object 
 2   age             156 non-null    float64
 3   nationality     156 non-null    object 
 4   province        156 non-null    object 
 5   current_state   166 non-null    object 
 6   contacted_with  27 non-null     float64
 7   confirmed_date  893 non-null    object 
 8   released_date   5 non-null      object 
 9   deceased_date   4 non-null      object 
 10  hospital        17 non-null     object 
dtypes: float64(2), int64(1), object(8)
memory usage: 76.9+ KB


#### Select 1 column

In [373]:
covid_19_gender = covid_19['gender'] # 1 column pada dataframe disebut Series

covid_19_gender.head()

0    female
1    female
2    female
3    female
4      male
Name: gender, dtype: object

In [408]:
type(covid_19_gender)

pandas.core.series.Series

#### Select multiple column

In [374]:
covid_19_compact = covid_19[['gender', 'age', 'province', 'current_state', 'confirmed_date', 'hospital']]

covid_19_compact.head()

gender   age     province current_state confirmed_date  \
0  female  31.0  DKI Jakarta      released       2-Mar-20   
1  female  64.0  DKI Jakarta      released       2-Mar-20   
2  female  33.0  DKI Jakarta      released       6-Mar-20   
3  female  34.0  DKI Jakarta      isolated       6-Mar-20   
4    male  55.0  DKI Jakarta      isolated       8-Mar-20   

               hospital  
0  RSPI Sulianti Saroso  
1  RSPI Sulianti Saroso  
2  RSPI Sulianti Saroso  
3  RSPI Sulianti Saroso  
4       RS Persahabatan

In [375]:
type(covid_19_compact)

pandas.core.frame.DataFrame

In [376]:
covid_19_compact.shape

(893, 6)

#### Filter Dataframe

In [377]:
covid_19_female = covid_19_compact[covid_19_compact['gender'] == 'female']

covid_19_female.head()

gender   age     province current_state confirmed_date  \
0  female  31.0  DKI Jakarta      released       2-Mar-20   
1  female  64.0  DKI Jakarta      released       2-Mar-20   
2  female  33.0  DKI Jakarta      released       6-Mar-20   
3  female  34.0  DKI Jakarta      isolated       6-Mar-20   
6  female  54.0  DKI Jakarta      released       9-Mar-20   

               hospital  
0  RSPI Sulianti Saroso  
1  RSPI Sulianti Saroso  
2  RSPI Sulianti Saroso  
3  RSPI Sulianti Saroso  
6                   NaN

In [378]:
covid_19_compact['gender'] == 'female'

0       True
1       True
2       True
3       True
4      False
       ...  
888    False
889    False
890    False
891    False
892    False
Name: gender, Length: 893, dtype: bool

In [379]:
covid_19_female.shape

(65, 6)

In [380]:
covid_19_DKI = covid_19_compact[covid_19_compact['province'] == 'DKI Jakarta']

covid_19_DKI.head()

gender   age     province current_state confirmed_date  \
0  female  31.0  DKI Jakarta      released       2-Mar-20   
1  female  64.0  DKI Jakarta      released       2-Mar-20   
2  female  33.0  DKI Jakarta      released       6-Mar-20   
3  female  34.0  DKI Jakarta      isolated       6-Mar-20   
4    male  55.0  DKI Jakarta      isolated       8-Mar-20   

               hospital  
0  RSPI Sulianti Saroso  
1  RSPI Sulianti Saroso  
2  RSPI Sulianti Saroso  
3  RSPI Sulianti Saroso  
4       RS Persahabatan

In [381]:
covid_19_DKI.shape

(124, 6)

In [382]:
covid_19_above_45 = covid_19_compact[covid_19_compact['age'] > 45]

covid_19_above_45.head()

gender   age     province current_state confirmed_date  \
1  female  64.0  DKI Jakarta      released       2-Mar-20   
4    male  55.0  DKI Jakarta      isolated       8-Mar-20   
6  female  54.0  DKI Jakarta      released       9-Mar-20   
7    male  55.0  DKI Jakarta      released       9-Mar-20   
8  female  55.0  DKI Jakarta      released       9-Mar-20   

               hospital  
1  RSPI Sulianti Saroso  
4       RS Persahabatan  
6                   NaN  
7                   NaN  
8                   NaN

In [383]:
covid_19_above_45.shape

(87, 6)

In [384]:
covid_19_DKI_male = covid_19_compact[(covid_19_compact['province'] == 'DKI Jakarta') & (covid_19_compact['gender'] == 'male')]

covid_19_DKI_male.head()

gender   age     province current_state confirmed_date  \
4    male  55.0  DKI Jakarta      isolated       8-Mar-20   
5    male  36.0  DKI Jakarta      released       8-Mar-20   
7    male  55.0  DKI Jakarta      released       9-Mar-20   
9    male  29.0  DKI Jakarta      isolated       9-Mar-20   
11   male  31.0  DKI Jakarta      isolated       9-Mar-20   

                hospital  
4        RS Persahabatan  
5        RS Persahabatan  
7                    NaN  
9   RSPI Sulianti Saroso  
11                   NaN

In [385]:
covid_19_DKI_male.shape

(67, 6)

- Ketika kita hendak menggabungkan lebih dari satu conditional statement, jangan lupa untuk menggunakan bracket `()`,
- selanjutnya kita tidak bisa menggunakan **or**/**and** operator untuk menggabuankan conditional statement, kita dapat menggunakan **|** untuk **or**, **&** untuk **and**.

#### Filter dengan fungsi isin()

In [392]:
covid_19_DKI_Banten = covid_19_compact[ covid_19_compact['province'].isin(['Banten', 'DKI Jakarta'])]

covid_19_DKI_Banten.head()

gender   age     province current_state confirmed_date  \
0  female  31.0  DKI Jakarta      released       2-Mar-20   
1  female  64.0  DKI Jakarta      released       2-Mar-20   
2  female  33.0  DKI Jakarta      released       6-Mar-20   
3  female  34.0  DKI Jakarta      isolated       6-Mar-20   
4    male  55.0  DKI Jakarta      isolated       8-Mar-20   

               hospital  
0  RSPI Sulianti Saroso  
1  RSPI Sulianti Saroso  
2  RSPI Sulianti Saroso  
3  RSPI Sulianti Saroso  
4       RS Persahabatan

In [394]:
covid_19_DKI_Banten.shape

(130, 6)

In [399]:
covid_19_DKI_Banten = covid_19_compact[(covid_19_compact['province'] == 'Banten') | 
                                       (covid_19_compact['province'] == 'DKI Jakarta')]

covid_19_DKI_Banten.head()

gender   age     province current_state confirmed_date  \
0  female  31.0  DKI Jakarta      released       2-Mar-20   
1  female  64.0  DKI Jakarta      released       2-Mar-20   
2  female  33.0  DKI Jakarta      released       6-Mar-20   
3  female  34.0  DKI Jakarta      isolated       6-Mar-20   
4    male  55.0  DKI Jakarta      isolated       8-Mar-20   

               hospital  
0  RSPI Sulianti Saroso  
1  RSPI Sulianti Saroso  
2  RSPI Sulianti Saroso  
3  RSPI Sulianti Saroso  
4       RS Persahabatan

In [400]:
covid_19_DKI_Banten.shape

(130, 6)

In [402]:
covid_19_compact_clean = covid_19_compact[covid_19_compact['age'].notna()]

covid_19_compact_clean.shape, covid_19_compact.shape

((156, 6), (893, 6))

#### Sorting Dataframe

In [403]:
covid_19_compact_clean.sort_values(by=["age"])

gender   age          province current_state confirmed_date hospital
53     male   2.0       DKI Jakarta      isolated      13-Mar-20      NaN
48     male   3.0     DI Yogyakarta      isolated      13-Mar-20      NaN
12   female  16.0       DKI Jakarta      released       9-Mar-20      NaN
15   female  17.0        Jawa Barat      isolated       9-Mar-20      NaN
156    male  19.0  Kalimantan Barat      isolated      17-Mar-20      NaN
..      ...   ...               ...           ...            ...      ...
68     male  80.0       DKI Jakarta      isolated      13-Mar-20      NaN
157  female  80.0       DKI Jakarta      isolated      17-Mar-20      NaN
37   female  80.0       DKI Jakarta      isolated      13-Mar-20      NaN
29     male  85.0       DKI Jakarta      isolated      11-Mar-20      NaN
80     male  86.0       DKI Jakarta      isolated      14-Mar-20      NaN

[156 rows x 6 columns]

In [404]:
covid_19_compact_clean.sort_values(by=["age"], ascending=False)

gender   age          province current_state confirmed_date hospital
80     male  86.0       DKI Jakarta      isolated      14-Mar-20      NaN
29     male  85.0       DKI Jakarta      isolated      11-Mar-20      NaN
68     male  80.0       DKI Jakarta      isolated      13-Mar-20      NaN
37   female  80.0       DKI Jakarta      isolated      13-Mar-20      NaN
157  female  80.0       DKI Jakarta      isolated      17-Mar-20      NaN
..      ...   ...               ...           ...            ...      ...
156    male  19.0  Kalimantan Barat      isolated      17-Mar-20      NaN
15   female  17.0        Jawa Barat      isolated       9-Mar-20      NaN
12   female  16.0       DKI Jakarta      released       9-Mar-20      NaN
48     male   3.0     DI Yogyakarta      isolated      13-Mar-20      NaN
53     male   2.0       DKI Jakarta      isolated      13-Mar-20      NaN

[156 rows x 6 columns]

In [407]:
covid_19_compact_clean.sort_values(by=["province", "age", ] , ascending=[True, False])

gender   age          province current_state confirmed_date  \
24   female  53.0              Bali      deceased      10-Mar-20   
58     male  63.0            Banten      isolated      13-Mar-20   
92     male  61.0            Banten      isolated      14-Mar-20   
34   female  57.0            Banten      deceased      13-Mar-20   
17     male  55.0            Banten      isolated       9-Mar-20   
..      ...   ...               ...           ...            ...   
140    male  22.0        Jawa Timur      isolated      17-Mar-20   
62     male  34.0  Kalimantan Barat      isolated      13-Mar-20   
156    male  19.0  Kalimantan Barat      isolated      17-Mar-20   
139    male  71.0    Kepulauan Riau      isolated      17-Mar-20   
61     male  51.0    Sulawesi Utara      isolated      13-Mar-20   

            hospital  
24        RS Sanglah  
58               NaN  
92               NaN  
34               NaN  
17   RS Persahabatan  
..               ...  
140              NaN  
62               NaN  
156              NaN  
139              NaN  
61               NaN  

[156 rows x 6 columns]

### Sumber :

- https://en.wikipedia.org/wiki/Matrix_%28mathematics%29#Basic_operations
- https://becominghuman.ai/an-essential-guide-to-numpy-for-machine-learning-in-python-5615e1758301
- https://data-flair.training/blogs/python-data-structures-tutorial/
- https://www.petanikode.com/tutorial/python/
- https://webcourses.ucf.edu/courses/1249560/pages/python-lists-vs-numpy-arrays-what-is-the-difference
- https://medium.com/@yunusmuhammad007/python-data-science-pandas-part-2-838797f00a96
- https://medium.com/@yunusmuhammad007/5-basic-python-programming-87c89e1d0d3e